### ISSUE TITLE
Have doctrine source read from entity meta data

### ISSUE THREAD

**Issue by oddz** [mesour/sources#12]
When I updated your packages yesterday I was blessed with all my grids running over a hundred queries. I began looking into the cause and discovered you are now using a schema discovery strategy that results in an absurd number of trips to the db. I think instead the discovery needs to come from the doctrine entity meta data.

**Comment by oddz** [comment]
The one grid I was testing was running about 280 queries. 95% of which were due to that new schema discovery strategy in doctrine source.

**Comment by oddz** [comment]
In doctrine source the method initializeDataStructure() is the culprit. I believe these two lines.

```
$tables = $schemaManager->listTables();
		$columns = $schemaManager->listTableColumns($this->getTableNameFromClassName($tableName));
```

**Comment by mesour** [comment]
Yes, i will fix it from entity meta data. This is the last thing which must be done before a stable version will be published :-)

**Comment by oddz** [comment]
cool

**Comment by oddz** [comment]
I'm not really a fan of having to define a method on each entity to convert to an an array. As an alternative I just decided to override the fetch methods with a array hydrator.

```
<?php namespace Modules\Core\Mesour\DataGrid\Sources;

use Mesour\DataGrid\Sources\DoctrineGridSource as BaseDoctrineGridSource;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\NoResultException;

class DoctrineGridSource extends BaseDoctrineGridSource {

    public function getReferencedSource($table, $callback = null, $tablePrefix = '_a0')
    {
        return parent::getReferencedSource(
            $table,
            $callback ? $callback : function () use ($table, $tablePrefix) {
                $tableStructure = $this->getDataStructure()->getTableStructure($table);
                $source = new DoctrineGridSource(
                    $tableStructure->getName(),
                    $tableStructure->getPrimaryKey(),
                    $this->getQueryBuilder()->getEntityManager()
                        ->createQueryBuilder()->select($tablePrefix)
                        ->from($table, $tablePrefix)
                );
                $source->setDataStructure($tableStructure);
                return $source;
            }
        );
    }

    public function fetchAll()
    {
        try {
            $this->lastFetchAllResult = $this->getQuery()->getResult(AbstractQuery::HYDRATE_ARRAY);
            return $this->lastFetchAllResult;

           /*return $this->fixResult(
                $this->getEntityArrayAsArrays($this->lastFetchAllResult)
            );*/
        } catch (NoResultException $e) {
            return [];
        }
    }

    public function fetchFullData($dateFormat = 'Y-m-d') {
        try {
            $allData = $this->lastFetchAllResult = $this->cloneQueryBuilder(true)
                ->setMaxResults(null)
                ->setFirstResult(null)
                ->getQuery()
                ->getResult(AbstractQuery::HYDRATE_ARRAY);

            /*$allData = $this->fixResult(
                $this->getEntityArrayAsArrays($this->lastFetchAllResult)
            );*/

            foreach ($allData as &$currentData) {
                foreach ($currentData as $key => $val) {
                    if ($val instanceof \DateTime) {
                        $currentData[$key] = $val->format($dateFormat);
                    }
                }
            }
            return $allData;
        } catch (NoResultException $e) {
            return [];
        }
    }

}
```

**Comment by mesour** [comment]
I fixed it and more in dev-master. It may cause exceptions, because it have BC break with current version if you used method addOneToOne. Method addManyToOne was added. Now it is clearer and everything is determined from class metadata.

Now i have to implement new features to grid and filter and can make mesour/sources stable :)

**Comment by oddz** [comment]
Cool, do you expect to release those changes on master soon?

**Comment by mesour** [comment]
Yes, now i can release stable version of mesour/sources, but i need first complete integration of mesour/editable to DataGrid and after create mesour/datagrid v3.1.*@beta, it will use the new sources

**Comment by oddz** [comment]
cool - I'm using your grid as part of an admin I'm working. Thanks for keeping me updated.

**Comment by mesour** [comment]
@oddz no problem :) I'm using it too :-) On sources is planned improvement for decrease count of SQL queries. Maybe i will create source for kdyby/doctrine - QueryObject. Here is documentation https://github.com/Kdyby/Doctrine/blob/master/docs/en/optimizing-query-objects.md but now it is part of kdyby/doctrine.

**Comment by mesour** [comment]
@oddz: I'm not really a fan of having to define a method on each entity to convert to an an array. As an alternative I just decided to override the fetch methods with a array hydrator.

Yes it is good for you, but more programmers need using entity methods in DataGrid callbacks :)

**All fixed**, sources are now stable as more mesour packages :-) Beta is now only Filter and DataGrid :) DataGrid have now implemented mesour/editable, but not complete ManyToMany and OneToMany edit buttons (reset,add, etc...).

**Comment by oddz** [comment]
cool

I updated the package and the number of queries seems to be back to normal.

**Comment by mesour** [comment]
super :)
